export const myProjects = [
    {
      id: "154",
      projectTitle: "VernChain",
      projectDescription: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid repellendus inventore iure tempore veniam minus fugit.",
      imgPath: "",
      projectDemo: "https://vernchain.netlify.app/",
      githubRepo: "",
      projectShowcase: "",
      category: ["react+tailwind"]
    },
    {
      id: "2654",
      projectTitle: "BestEats",
      projectDescription: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid repellendus inventore iure tempore veniam minus fugit.",
      imgPath: "",
      projectDemo: "https://besteats-ahmed.netlify.app",
      githubRepo: "",
      projectShowcase: "",
      category: ["react+tailwind"]
    },
    {
      id: "8994",
      projectTitle: "Rocketeer Helmets",
      projectDescription: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid repellendus inventore iure tempore veniam minus fugit.",
      imgPath: "",
      projectDemo: "https://rocketeerhelmets.netlify.app",
      githubRepo: "",
      projectShowcase: "",
      category: ["html&css"]
    },
    {
      id: "64866",
      projectTitle: "Nexcent Agency",
      projectDescription: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid repellendus inventore iure tempore veniam minus fugit.",
      imgPath: "",
      projectDemo: "https://nextcent-as.netlify.app",
      githubRepo: "",
      projectShowcase: "",
      category: ["react+tailwind"]
    },
    {
      id: "684798",
      projectTitle: "College Education Website",
      projectDescription: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid repellendus inventore iure tempore veniam minus fugit.",
      imgPath: "",
      projectDemo: "https://college-website-tuts.netlify.app",
      githubRepo: "",
      projectShowcase: "",
      category:  ["javascript"],
    },
    {
      id: "628764839",
      projectTitle: "Cryptoverse",
      projectDescription: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid repellendus inventore iure tempore veniam minus fugit.",
      imgPath: "",
      projectDemo: "https://college-website-tuts.netlify.app",
      githubRepo: "",
      projectShowcase: "",
      category:  ["react"],
    },
    {
      id: "9845737",
      projectTitle: "Password Strength Checker",
      projectDescription: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid repellendus inventore iure tempore veniam minus fugit.",
      imgPath: "",
      projectDemo: "https://passwordstrength-salawu.netlify.app",
      githubRepo: "",
      projectShowcase: "",
      category: ["html&css"],
    },
    {
      id: "4653774",
      projectTitle: "Horizontal Tabs",
      projectDescription: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid repellendus inventore iure tempore veniam minus fugit.",
      imgPath: "",
      projectDemo: "https://horizontaltabs-salawu.netlify.app/",
      githubRepo: "",
      projectShowcase: "",
      category: ["html&css"],
    },
    {
      id: "986498738",
      projectTitle: "Custom Drop Menu",
      projectDescription: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid repellendus inventore iure tempore veniam minus fugit.",
      imgPath: "",
      projectDemo: "https://customdropmenu-salawu.netlify.app/",
      githubRepo: "",
      projectShowcase: "",
      category: ["html&css"],
    },
    {
      id: "9264782537",
      projectTitle: "Saas Pricing Page",
      projectDescription: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid repellendus inventore iure tempore veniam minus fugit.",
      imgPath: "",
      projectDemo: "https://saaspricingpage.netlify.app/",
      githubRepo: "",
      projectShowcase: "",
      category: ["html&css"],
    },
    {
      id: "52763276",
      projectTitle: "Coffee Website",
      projectDescription: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid repellendus inventore iure tempore veniam minus fugit.",
      imgPath: "",
      projectDemo: "https://coffeewebsite-salaw.netlify.app/",
      githubRepo: "",
      projectShowcase: "",
      category: ["html&css"],
    },
    {
      id: "523462",
      projectTitle: "Accordion Menu",
      projectDescription: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid repellendus inventore iure tempore veniam minus fugit.",
      imgPath: "",
      projectDemo: "https://accordion-salawu.netlify.app/",
      githubRepo: "",
      projectShowcase: "",
      category: ["html&css"],
    },
    {
      id: "439754",
      projectTitle: "Character Counter",
      projectDescription: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid repellendus inventore iure tempore veniam minus fugit.",
      imgPath: "",
      projectDemo: "https://charactercounter-salawu.netlify.app/",
      githubRepo: "",
      projectShowcase: "",
      category: ["javascript"],
    },
    {
      id: "3243562",
      projectTitle: "Budget Expense",
      projectDescription: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid repellendus inventore iure tempore veniam minus fugit.",
      imgPath: "",
      projectDemo: "https://budgettracker-salawu.netlify.app/",
      githubRepo: "",
      projectShowcase: "",
      category: ["react"],
    },
  ]